graph [
    node [ id 1 label "H" ]
    node [ id 2 label "O" ]
    node [ id 3 label "O" ]
    node [ id 4 label "P" ]
    node [ id 5 label "O" ]
    node [ id 6 label "H" ]
    node [ id 7 label "O" ]
    node [ id 8 label "C" ]
    node [ id 9 label "H" ]
    node [ id 10 label "H" ]
    node [ id 11 label "C" ]
    node [ id 12 label "C" ]
    node [ id 13 label "H" ]
    node [ id 14 label "O" ]
    node [ id 15 label "H" ]
    node [ id 16 label "H" ]
    node [ id 17 label "O" ]
    node [ id 18 label "O" ]
    node [ id 19 label "C" ]
    node [ id 20 label "C" ]
    node [ id 21 label "O" ]
    node [ id 22 label "H" ]
    node [ id 23 label "H" ]
    node [ id 24 label "H" ]
    node [ id 25 label "H" ]

    edge [ source 1 target 2 label "-" ]
    edge [ source 2 target 4 label "-" ]
    edge [ source 4 target 3 label "=" ]
    edge [ source 4 target 5 label "-" ]
    edge [ source 4 target 7 label "-" ]
    edge [ source 5 target 6 label "-" ]
    edge [ source 7 target 8 label "-" ]
    edge [ source 8 target 9 label "-" ]
    edge [ source 8 target 10 label "-" ]
    edge [ source 8 target 11 label "-" ]
    edge [ source 11 target 14 label "-" ]
    edge [ source 11 target 25 label "-" ]
    edge [ source 11 target 12 label "-" ]
    edge [ source 14 target 15 label "-" ]
    edge [ source 12 target 17 label "-" ]
    edge [ source 12 target 13 label "-" ]
    edge [ source 17 target 16 label "-" ]
    edge [ source 12 target 19 label "-" ]
    edge [ source 19 target 18 label "=" ]
    edge [ source 19 target 20 label "-" ]
    edge [ source 20 target 21 label "-" ]
    edge [ source 20 target 24 label "-" ]
    edge [ source 20 target 23 label "-" ]
    edge [ source 21 target 22 label "-" ]
]